<a href="https://colab.research.google.com/github/April-LY/prublue/blob/master/sinceri_program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import pandas as pd
from pathlib import Path
import numpy as np

In [3]:
class DATA():
  def __init__(self, time, num_time_points, totDATA, timeline, numGENES, genes,singleCELLdata):
    self.time = time
    self.num_time_points = num_time_points
    self.totDATA = totDATA
    self.timeline = timeline
    self.numGENES = numGENES
    self.genes = genes
    self.singleCELLdata = singleCELLdata
    ''' a error maybe the siglecelldata format'''

In [4]:
def uploading():
  Whole_Data = pd.read_csv('/content/THP1_single_cell_data.csv')
  Whole_Data = pd.DataFrame(Whole_Data)

  #acquire gene name and the number of genes
  genes = Whole_Data.keys()
  genes = genes[0:-1]
  numGENES = len(genes)
  #print(genes)

  #delete the na column
  '''Q:different pesudotime the na value of the same cell
  will the condition be the same'''

  Whole_Data.dropna(axis = 1,how = "any",inplace = True)
  #print(Whole_Data)

  #totDATA delete the column of time--the last column
  Whole_Data = Whole_Data.values
  print(Whole_Data)
  totData = Whole_Data[:,0:-1]
  #print(totData)

  #timeline extract all of the time point
  timeline = Whole_Data[:,-1]
  #print(timeline)
  
  #Data.time euqals to different time type
  #number of different pesudotime
  time = list(set(timeline))
  time.sort()
  print("-----------")
  print(time)
  num_time_points = len(time)

  sortTOTdata = []
  sortTIMELINE = []
  
  for k in range(num_time_points):
    I = np.where(timeline == time[k])
    sortTOTdata.append(totData[I,:])
    sortTIMELINE.append(timeline[I])
  print(sortTOTdata)
  print(sortTIMELINE[0])

  totDATA=sortTOTdata
  timeline=sortTIMELINE

  '''lack the function of adding the default name'''
  singleCELLdata = sortTOTdata
  dt = DATA(time, num_time_points, totData, timeline, numGENES, genes, singleCELLdata)
  return dt

DATA = uploading()
#print(dt.time) 

[[ 8.6953699  9.1754934  8.4145353 ... 13.7060081  8.3097131  0.       ]
 [14.0241672  8.2617432 12.6212516 ... 15.9133078  4.0480262  0.       ]
 [ 3.9539206  9.3483853  3.9539206 ... 18.9207062  3.9539206  0.       ]
 ...
 [22.5864836  7.9996349 11.9851245 ...  3.8497197  8.0481192 96.       ]
 [30.2255601  9.4110804  9.7783701 ... 13.959202   9.8297607 96.       ]
 [33.7970302 10.5759922 12.7840582 ... 10.7744225  9.6583099 96.       ]]
-----------
[0.0, 1.0, 6.0, 12.0, 24.0, 48.0, 72.0, 96.0]
[array([[[ 8.6953699,  9.1754934,  8.4145353, ..., 12.9472126,
         13.7060081,  8.3097131],
        [14.0241672,  8.2617432, 12.6212516, ..., 14.0301398,
         15.9133078,  4.0480262],
        [ 3.9539206,  9.3483853,  3.9539206, ..., 13.5478473,
         18.9207062,  3.9539206],
        ...,
        [10.457901 ,  9.0906098,  8.4633917, ..., 12.5913521,
         14.7737557,  3.8217655],
        [12.0211424, 12.1078583, 11.3680552, ..., 14.0509424,
         13.1727074,  8.6176433],
    

# 新段落

'''
  if not genes:
    for i in range(numGENES):
      genes[i] = sprintf('Gene %d',i)
  else:
    genes = Whole_Data.keys()
    genes = genes[1:-1]
'''

In [ ]:
from scipy import stats

In [5]:
from scipy import stats
'''
Parameter settings:
  distance: this parameter selects the distribution distance
    1- for KS (Kolmogorov-Smirnov)  (* DEFAULT *)
    2- for CM (Cramer-von Mises)
    3- for AD (Anderson-Darling)

  method: this parameter selects the regularization regression strategy
    1- for RIDGE  (* DEFAULT *)
    2- for ELASTIC-NET with automatic detection of optimal alpha parameter
    3- for LASSO
    4- for ELASTIC-NET with manual selection of alpha parameter

  noDIAG: this parameter selects whether the auto-regulatory edge is inferred
    0- GRN contains auto-regulatory edges (* DEFAULT *)
    1- GRN contains no auto-regulatory edge
   
  SIGN: this parameter selects whether the sign / mode of the gene regulations is inferred
    0- for unsigned GRN
    1- for signed GRN (* DEFAULT *)
  
'''
def SINCERIETIES(DATA,distance = 1,method = 1,noDIAG = 0,SIGN = 1):

  ##Check input arguments
  if distance not in range(1,4):
    print("Choose distance metric with 1,2 and 3: 1 for Kolmogorov-Smirnov(KM), 2 for Cramer-von Mises(CM), 3 for Anderson-Darling(AD)")

  ##Initialization
  time = DATA.time
  single_cell_data = DATA.singleCELLdata
  numGENES = DATA.numGENES
  num_time_points = len(time)

  ##catch error
  '''
  if num_time_points < 5:
    print("'** DATA with a number of time points < 5. Please run SINCERITIES_CROSS_VALIDATION function **")
  '''

  #Distribution distance
  #Distance_matrix = np.arange(120).reshape(num_time_points-1,numGENES)
  Distance_matrix = np.zeros(shape = (num_time_points-1,numGENES))
  
  #print(Distance_matrix)
  totalDATA = single_cell_data[0]
  print(totalDATA) 
  #print(single_cell_data[1])

  '''cmtest2'''

  for ti in range(0,num_time_points-1):
    totalDATA = np.append(totalDATA,single_cell_data[ti+1])
    data_ti = single_cell_data[ti].T
    data_ti_plus1 = single_cell_data[ti+1].T
    
    for gi in range(0,numGENES):
      p1 = data_ti[gi,:]
      p2 = data_ti_plus1[gi,:]
      if distance == 1:
        p1 = p1.flatten()
        p2 = p2.flatten()
        #print(p2)
        test_stat = stats.ks_2samp(p1,p2)
        #print(test_stat.statistic)
        Distance_matrix[ti,gi] = test_stat.statistic
    
  ######################
  ##normalization
  #####################
  print(DATA.time[1:])
  print(DATA.time[0:-1])
  templist = list(map(lambda x: x[0]-x[1], zip(DATA.time[1:], DATA.time[0:-1])))
  templist
  dim1 = np.shape(Distance_matrix)[1]
  dim2 = np.shape(Distance_matrix)[0]
  flatten_temp_array = templist * dim1
  #print(x)
  #print(y)
  deltaT = np.reshape(flatten_temp_array,(dim1,dim2)).T
  Distance_matrix_normed = Distance_matrix/deltaT
  #print(Distance_matrix_normed)
  #print(deltaT)

  #############################
  #Generate Y and X_matrix for glmnet
  #method = 1 ridge
  #############################
  
  alphas = 0
  Distance_matrix = Distance_matrix_normed
  X_matrix = Distance_matrix[0:num_time_points-2,]
  #print(X_matrix)

  ###################
  #LOOCV settings
  ####################
  nfold = np.shape(X_matrix)[0]
  foldid = range(1,nfold+1)
  
  keep = True
  print(numGENES)
  pred_lambda_min = np.zeros((numGENES,numGENES))
  print(pred_lambda_min)
  '''  
  lack elseif
  print(totalDATA) 
  a = range(0,num_time_points-1)
  print(a)
  '''
  import sklearn
  from sklearn.linear_model import Ridge
  for gi in range(0,numGENES):
    cvlambda = []
    cvERROR = []
    beta = np.zeros((np.shape(X_matrix)[1],len(alphas)))

    for test in range(1,len(alphas)):
      Y_vector = Distance_matrix[1:num_time_points-1,gi]
      ###############################
      # 创建岭回归拟合
      ###############################
      ri = Ridge(alpha=alphas[test])
      ri.fit(X_matrix, Y_vector)

      ###############################
      # 寻找最优lambda
      ###############################
      cvlambda[test] = ri.coef_

      ###############################
      # 没看懂
      ###############################
      cv_results = 
      cvlambda[test] = cv_results?




In [7]:
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LassoCV, LassoLarsCV, LassoLarsIC
from sklearn import datasets


SyntaxError: ignored

In [6]:
SINCERIETIES(DATA)

[[[ 8.6953699  9.1754934  8.4145353 ... 12.9472126 13.7060081  8.3097131]
  [14.0241672  8.2617432 12.6212516 ... 14.0301398 15.9133078  4.0480262]
  [ 3.9539206  9.3483853  3.9539206 ... 13.5478473 18.9207062  3.9539206]
  ...
  [10.457901   9.0906098  8.4633917 ... 12.5913521 14.7737557  3.8217655]
  [12.0211424 12.1078583 11.3680552 ... 14.0509424 13.1727074  8.6176433]
  [10.8013065  8.4488772  9.3184681 ... 12.7281134 18.4899218  8.9175179]]]
[1.0, 6.0, 12.0, 24.0, 48.0, 72.0, 96.0]
[0.0, 1.0, 6.0, 12.0, 24.0, 48.0, 72.0]
45
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
import glmnet

     |████████████████████████████████| 1.6MB 8.4MB/s 


In [ ]:
def main():

  Data = uploading()

  adj_matrix = SINCERIETIES(Data)
  
  return adj_matrix


In [ ]:
class DATA():
  def __init__(self, time, num_time_points, totDATA, timeline, numGENES, genes, singleCELLdata)
    self.time = time
    self.num_time_points = num_time_points
    self.totDATA = totDATA
    self.timeline = timeline
    self.numGENES = numGENES
    self.genes = genes
    self.singleCELLdata = singleCELLdata


SyntaxError: ignored

In [ ]:
??stats.kstest